using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Dapper;

namespace IntergalacticPassportAPI.Models
{
	[Table("statuses")]
	public class Status
	{
		[PrimaryKey(AutoGenerated = true)]
        [Column("id")]
        public int Id { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("reason")]
        public string? Reason { get; set; }

        public Status(String name, String reason){
            this.Name = name;
            this.Reason = reason;
        }

        public Status(int id, String name, String reason){
            this.Id = id;
            this.Name = name;
            this.Reason= reason;
        }

	}
}
