using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Dapper;

namespace IntergalacticPassportAPI.Models
{
    public class Users
    {
        [PrimaryKey(AutoGenerated = false)]
        [Column("google_id")]
        public string? google_id{ get; set; }

        [Column("email")]
        public string? email { get; set; }
        
        [Column("name")]
        public string? name { get; set; }

        [Column("species")]
        public string? species { get; set; }

        [Column("planet_of_origin")]
        public string? planet_of_origin { get; set; }
        [Column("primary_language")]
        public string? primary_language { get; set; }
        [Column("date_of_birth")]
        public DateTime? date_of_birth { get; set; }
    }
}
